-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    "IdCliente" integer NOT NULL DEFAULT nextval('clientes_idcliente_seq'::regclass),
    "Nombres" character varying(100) COLLATE pg_catalog."default",
    "Apellidos" character varying(100) COLLATE pg_catalog."default",
    "Email" character varying(100) COLLATE pg_catalog."default",
    "Telefono" character varying(20) COLLATE pg_catalog."default",
    "Direccion" character varying(200) COLLATE pg_catalog."default",
    "CodigoPostal" character varying(10) COLLATE pg_catalog."default",
    "Barrio" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY ("IdCliente")
);

CREATE TABLE IF NOT EXISTS public.detalleventas
(
    "IdDetalleVenta" integer NOT NULL DEFAULT nextval('detalleventas_iddetalleventa_seq'::regclass),
    "IdVenta" integer,
    "SKU" integer,
    "Cantidad" integer,
    CONSTRAINT detalleventas_pkey PRIMARY KEY ("IdDetalleVenta")
);

CREATE TABLE IF NOT EXISTS public.productos
(
    "SKU" integer NOT NULL DEFAULT nextval('productos_sku_seq'::regclass),
    "Nombre" character varying(100) COLLATE pg_catalog."default",
    "Descripcion" text COLLATE pg_catalog."default",
    "Precio" numeric(10, 2),
    CONSTRAINT productos_pkey PRIMARY KEY ("SKU")
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    "IdVenta" integer NOT NULL DEFAULT nextval('ventas_idventa_seq'::regclass),
    "IdCliente" integer,
    "FechaVenta" date,
    CONSTRAINT ventas_pkey PRIMARY KEY ("IdVenta")
);

ALTER TABLE IF EXISTS public.detalleventas
    ADD CONSTRAINT detalleventas_idventa_fkey FOREIGN KEY ("IdVenta")
    REFERENCES public.ventas ("IdVenta") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalleventas
    ADD CONSTRAINT detalleventas_sku_fkey FOREIGN KEY ("SKU")
    REFERENCES public.productos ("SKU") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_idcliente_fkey FOREIGN KEY ("IdCliente")
    REFERENCES public.clientes ("IdCliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;